export default {
  editCell: 'enter',
  rename: 'f2',
  moveUp: 'up',
  moveDown: 'down',
  moveLeft: ['left', 'shift+tab'],
  moveRight: ['right', 'tab'],
  massSelectDown: 'shift+down',
  massSelectUp: 'shift+up',
  massSelectLeft: 'shift+left',
  massSelectRight: 'shift+right',
  initSelection: { sequence: 'shift', action: 'keydown' },
  endSelection: { sequence: 'shift', action: 'keyup' },
  exitEdit: 'escape',
  closeForm: 'escape',
  openForm: 'shift+space',
  stageChanges: 'enter',
  removeRow: 'shift+del',
  addNew: 'mod+a',
  checkRow: 'mod+space',
  selectItem: 'enter',
  save: ['mod+s'],
  delete: ['del', 'backspace'],
  undo: ['mod+z'],
  redo: ['mod+shift+z', 'mod+y'],
  konami: 'up up down down left right left right b a',
  space: 'space',
  copy: ['mod+c'],
  paste: ['mod+v'],
  pasteRows: 'mod+shift+v',
}
